[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#b91c1c"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "serif"
